---

- name: apt cache updated
  apt: update_cache=True cache_valid_time=86400

- name: unattended-upgrades package is installed
  apt: pkg=unattended-upgrades state=installed

- name: unattended-upgrades is configured
  template: src=unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: configure unattended-upgrades to allow autoupgrade
  dpkg_reconfigure:
    pkg: unattended-upgrades
    answers:
      unattended-upgrades/enable_auto_updates: true
