---

- name: bash is default shell
  debconf:
    name: dash
    question: "dash/sh"
    value: "false"
    vtype: boolean

- name: copy .bashrc
  copy:
    src: .bashrc
    dest: /root/.bashrc
    mode: 0644
