---

- name: Ensure fail2ban is present
  apt:
    name: fail2ban
    state: present
- name: Ensure log level is set to NOTICE
  lineinfile:
    dest: /etc/fail2ban/fail2ban.conf
    regexp: "^loglevel ="
    line: "loglevel = NOTICE"
  notify:
   - restart fail2ban
- name: Ensure Admin IP is present in jail.conf
  lineinfile:
    dest: /etc/fail2ban/jail.conf
    regexp: "^ignoreip ="
    line: "ignoreip = 127.0.0.1/8 {{ allow_global_ip }}/32"
  notify:
   - restart fail2ban
