---

- name: newrelic repository key is present
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: newrelic repository is present
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present update_cache=true

- name: newrelic-sysmond is installed
  apt: pkg=newrelic-sysmond state=present

- name: newrelic license key is present
  lineinfile: dest=/etc/newrelic/nrsysmond.cfg regexp=^license_key= line=license_key={{ newrelic_license_key }}
  notify:
   - restart newrelic-sysmond

- name: newrelic-sysmond is running
  service: name=newrelic-sysmond state=running enabled=yes
