---

- name: Check if python synlink is present
  raw: test -f /usr/bin/python
  register: python_binary
  ignore_errors: true

- name: Check if python3 is installed
  raw: test -f /usr/bin/python3
  register: python3_binary
  ignore_errors: true

- name: Link python
  raw: ln -s /usr/bin/python3 /usr/bin/python
  when: python_binary.failed and not python3_binary.failed

- name: Gathering facts
  setup:
