---

- name: Limit for /var/log/journal directory is set
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse={{ systemd_journal_max_size }}"
  notify:
   - restart journald
